name: Docker Base Auto Update CI

on:
  schedule:
  - cron: "23 13 3 * *"

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/arm64

    steps:
    - 
      name: Docker Image Update Checker
      id: baseupdatecheck
      uses: lucacome/docker-image-update-checker@v1
      with:
        base-image: library/golang:alpine
        image: simeononsecurity/chirpstack-packet-multiplexer:latest
    -
        name: Checkout
        uses: actions/checkout@v4
        if: steps.check.outputs.needs-updating == 'true'
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.check.outputs.needs-updating == 'true'
    -
        name: setup docker buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
        if: steps.check.outputs.needs-updating == 'true'
    -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: steps.check.outputs.needs-updating == 'true'
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        file: Dockerfile
        cache-from: |
          type=gha .
          type=inline .
          simeononsecurity/chirpstack-packet-multiplexer:latest
          type=registry,ref=simeononsecurity/chirpstack-packet-multiplexer:latest
        cache-to: |
          type=registry,ref=simeononsecurity/chirpstack-packet-multiplexer:latest
        tags: simeononsecurity/chirpstack-packet-multiplexer:latest
      if: steps.check.outputs.needs-updating == 'true'
