name: Docker Image CI - Middleman

on:
  push:
    branches: [middleman]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'middleman'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build --platform linux/amd64,linux/arm64 -t simeononsecurity/chirpstack-packet-multiplexer:middleman --progress=plain --push .
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: simeononsecurity/chirpstack-packet-multiplexer:middleman
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build the simeononsecurity/chirpstack-packet-multiplexer:middleman Docker image for Github Registry
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/simeononsecurity/chirpstack-packet-multiplexer:middleman --progress=plain --push .
