name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.PAT_TOKEN }}"

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: "${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}"

      - name: Run tests
        run: nix-shell --command "make test"

      - name: Build project
        run: nix-shell --command "make build"

      - name: Build distributables
        run: nix-shell --command "make dist"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: chirpstack/chirpstack-packet-multiplexer

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          sbom: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: Dockerfile
          tags: |
            simeononsecurity/chirpstack-packet-multiplexer:latest
            ghcr.io/simeononsecurity/chirpstack-packet-multiplexer:latest
          github-token: "${{ secrets.PAT_TOKEN }}"

      - name: Image digest
        run: echo "Docker image digest: ${{ steps.docker_build.outputs.digest }}"
